Table Members {
    member_id int [pk]
    member_name varchar
    global_score int
}

Table Leaderboards {
    leaderboard_id int [pk]
    leaderboard_owner int [ref: > Members.member_id]
    event int [ref: > Events.year]
    api_key varchar
}

Table Events {
    year int
}

Table Memberships {
    member_id int [ref: > Members.member_id]
    leaderboard_id int [ref: > Leaderboards.leaderboard_id]
    local_score int
}

Table Score {
    score_id int [pk, increment]
    member_id int [ref: > Members.member_id]
    event int [ref: > Events.year]
    score blob [note: '100 bits']
}